# 로컬 개발용
services:
    mysql:
        image: mysql:8.0
        container_name: tickenity-mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql/data:/var/lib/mysql
            - ./db/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: dev
            MYSQL_ROOT_PASSWORD: 1234
    
    redis:
        image: redis:7.2
        container_name: tickenity-redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./db/redis/data:/data
